project:
  type: book
  output-dir: docs

book:
  title: "Sprint de Agosto"
  author: ""
  date: "8/9/2025"
  chapters:
    - index.qmd
    - etapas.qmd
    - CIDs.qmd
    - HAS.qmd
    - DM.qmd
    - CI.qmd
    - ICC.qmd
    - IRC.qmd
    - MM.qmd
    - PoliF.qmd
    - fragil.qmd
    - pilula_CI.qmd
    - pilulas_IC.qmd
    - implementacao.qmd
    - rastreios.qmd
    - pente_fino_DM.qmd
    - pente_fino_HAS.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

